# -*- coding: utf-8 -*-
"""Python intro Pre-work

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJvOMyGfWJEBYiKz7LCCDalvCnLUS5Ew
"""

# Weight Verifier for Blood Donation
name = input("Enter Name: ")
weight = float(input("Enter Weight: "))
if weight >= 120:
  print("Hi! " + name + " you weigh, " + str(weight) + "lb and therefore eligible to donate blood.")
else:
  print("Hi! " + name + " you weigh, " + str(weight) + "lb and therefore, not eligible to donate blood.")

#Example 1
#Input Kris; 109.11
#Output Hi! Kris you weigh, 109.11lb and therefore not eligible to donate blood.

#Example 2
#Input Winnie; 132.34
#Output Hi! Winnie you weigh, 132.34lb and therefore eligible to donate blood.

